<?php

/**
 * @file
 * Provides file system integration for Dropbox.
 */

/**
 * Implements hook_stream_wrappers().
 */
function dropboxfs_stream_wrappers() {
  return array(
    'dropboxfs' => array(
      'name' => 'Dropbox File System',
      'class' => 'DropboxFSStreamWrapper',
      'description' => t('Dropbox Storage'),
    ),
  );
}

/**
 * Implements hook_libraries_info()
 */
function dropboxfs_libraries_info() {
  return array(
    'dropbox-sdk-php' => array(
      'title' => 'Dropbox SDK for PHP',
      'vendor url' => 'https://github.com/dropbox/dropbox-sdk-php',
      'download url' => 'https://github.com/dropbox/dropbox-sdk-php/archive/v1.1.2.zip',
      'version arguments' => array(
        'file' => 'ChangeLog.txt',
        'pattern' => "/([0-9]*\.[0-9]*\.[0-9]*)/",
        'lines' => 2,
      ),
      'xautoload' => '_dropboxfs_xautoload'
    ),
  );
}

function _dropboxfs_xautoload($api) {
  return $api->namespaceRoot("Dropbox", "lib");
}
